using Content.Client.Administration.Managers;
using Content.Client.Audio;
using Content.Shared.CCVar;
using Robust.Client.Audio;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;
using Content.Shared._EE.CCVar; // EE
using Content.Shared._VDS.CCVars;
using Content.Client.UserInterface.ControlExtensions; // VDS

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class AudioTab : Control
{
    [Dependency] private readonly IAudioManager _audio = default!;
    [Dependency] private readonly IClientAdminManager _admin = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public AudioTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var masterVolume = Control.AddOptionPercentSlider(
            CVars.AudioMasterVolume,
            SliderVolumeMaster,
            scale: ContentAudioSystem.MasterVolumeMultiplier);
        masterVolume.ImmediateValueChanged += OnMasterVolumeSliderChanged;

        Control.AddOptionPercentSlider(
            CVars.MidiVolume,
            SliderVolumeMidi,
            scale: ContentAudioSystem.MidiVolumeMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbientMusicVolume,
            SliderVolumeAmbientMusic,
            scale: ContentAudioSystem.AmbientMusicMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.AmbienceVolume,
            SliderVolumeAmbience,
            scale: ContentAudioSystem.AmbienceMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.LobbyMusicVolume,
            SliderVolumeLobby,
            scale: ContentAudioSystem.LobbyMultiplier);

        Control.AddOptionPercentSlider(
            CCVars.InterfaceVolume,
            SliderVolumeInterface,
            scale: ContentAudioSystem.InterfaceMultiplier);

        // ee add
        Control.AddOptionPercentSlider(
            EECCVars.AnnouncerVolume,
            SliderVolumeAnnouncer,
            scale: ContentAudioSystem.AnnouncerMultiplier);

        Control.AddOptionSlider(
            CCVars.MaxAmbientSources,
            SliderMaxAmbienceSounds,
            _cfg.GetCVar(CCVars.MinMaxAmbientSourcesConfigured),
            _cfg.GetCVar(CCVars.MaxMaxAmbientSourcesConfigured));

        Control.AddOptionCheckBox(CCVars.LobbyMusicEnabled, LobbyMusicCheckBox);
        Control.AddOptionCheckBox(CCVars.RestartSoundsEnabled, RestartSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.EventMusicEnabled, EventMusicCheckBox);

        // ee add
        Control.AddOptionCheckBox(EECCVars.AnnouncerDisableMultipleSounds, AnnouncerDisableMultipleSoundsCheckBox);

        Control.AddOptionCheckBox(CCVars.AdminSoundsEnabled, AdminSoundsCheckBox);
        Control.AddOptionCheckBox(CCVars.BwoinkSoundEnabled, BwoinkSoundCheckBox);

        // VDS start
        var acousticEnable = Control.AddOptionCheckBox(VCCVars.AdvanceAudioToggle, AcousticEnableCheckBox);
        acousticEnable.ImmediateValueChanged += UpdateAcousticButtons;

        Control.AddOptionCheckBox(VCCVars.AARaycastHighResolution, AcousticHighResolutionCheckBox);
        Control.AddOptionSlider(
            VCCVars.AARaycastReflectionCount,
            SliderAcousticReflectionCount,
            _cfg.GetCVar(VCCVars.AARaycastReflectionCountMinimum),
            _cfg.GetCVar(VCCVars.AARaycastReflectionCountMaximum));

        var acousticPressureEnable = Control.AddOptionCheckBox(VCCVars.AAFilterPressureToggle, AcousticEnableLowPressureFilterCheckBox);
        acousticPressureEnable.ImmediateValueChanged += UpdateAcousticPressureFilterButtons;

        var pressureMinVolumeSlider = Control.AddOptionPercentSlider(
            VCCVars.AAFilterPressureMinimumGain,
            SliderAcousticLowPressureMinimumVolume);
        pressureMinVolumeSlider.ImmediateValueChanged += OnAcousticLowPressureMinVolumeSliderChanged;
        // VDS end

        Control.Initialize();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _admin.AdminStatusUpdated += UpdateAdminButtonsVisibility;
        UpdateAdminButtonsVisibility();
        UpdateAcousticButtons(_cfg.GetCVar(VCCVars.AdvanceAudioToggle)); // VDS
        UpdateAcousticPressureFilterButtons(
                _cfg.GetCVar(VCCVars.AdvanceAudioToggle)
                && _cfg.GetCVar(VCCVars.AAFilterPressureToggle)); // VDS
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _admin.AdminStatusUpdated -= UpdateAdminButtonsVisibility;
    }

    private void UpdateAdminButtonsVisibility()
    {
        BwoinkSoundCheckBox.Visible = _admin.IsActive();
    }

    private void UpdateAcousticButtons(bool value) // VDS
    {
        AcousticSettingsContainer.Visible = value is true;
        // AcousticHighResolutionCheckBox.Visible = value is true;
        // SliderAcousticReflectionCount.Visible = value is true;
        // AcousticsWipWarningLabel.Visible = value is true;
        // AcousticEnableLowPressureFilterCheckBox.Visible = value is true;
    }

    private void UpdateAcousticPressureFilterButtons(bool value) // VDS
    {
        AcousticLowPressureSettingsContainer.Visible = value is true;
    }

    private void OnAcousticLowPressureMinVolumeSliderChanged(float value) // VDS
    {
        if (value == 0f)
            AcousticLowPressureSubtext.Text = Loc.GetString("ui-options-acoustics-low-pressure-subtext-zero-volume");
        else if (value == 1f)
            AcousticLowPressureSubtext.Text = Loc.GetString("ui-options-acoustics-low-pressure-subtext-max-volume");
        else
            AcousticLowPressureSubtext.Text = " ";
    }

    private void OnMasterVolumeSliderChanged(float value)
    {
        // TODO: I was thinking of giving OptionsTabControlRow a flag to "set CVar immediately", but I'm deferring that
        // until there's a proper system for enforcing people don't close the window with pending changes.
        _audio.SetMasterGain(value);
    }
}
